# ▼ ここで矢印の色(fg)をディレクトリの背景色と合わせるのがポイントです
format = """
$directory\
[ ](fg:#bb9af7 bg:#1d2230)\
$git_branch\
$git_status\
[ ](fg:#1d2230)\
\n$character
"""

right_format = """
$cmd_duration\
$username\
$custom.sparkles\
$time
"""

add_newline = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false

[fill]
symbol = " "

[directory]
# ▼ ここで背景色(bg)を水色(#88C0D0)から紫(#bb9af7)に変更しました
# 文字色(fg)はコントラストのために濃い色(#1a1b26)にしています
style = "fg:#1a1b26 bg:#bb9af7 bold"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " 󰌾 "
read_only_style = "fg:#f7768e bg:#1a1b26"
format = "[ $path ]($style)[$read_only]($read_only_style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bg:#1d2230"
format = "[[ $symbol $branch ](fg:#769ff0 bg:#1d2230)]($style)"

[git_status]
style = "bg:#1d2230"
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#1d2230)]($style)"

[cmd_duration]
min_time = 1
style = "fg:#e0af68"
format = "[$duration]($style)"

[time]
disabled = false
time_format = "%R"
format = "[[   $time ](fg:#a0a9cb)]($style)"

[character]
vimcmd_symbol = "[V](bold green) "

[custom.sparkles]
command = "echo ✨"
when = "true"
format = "$output"